#========================================server config=====================================
server:
  port: 9100
#========================================dubbo config=====================================
dubbo:
  application:
    id: fescar-dubbo-account
    name: fescar-dubbo-account
    qos-enable: false
  protocol:
    id: dubbo
    name: dubbo
    port: 20882
  registry:
    id: fescar-dubbo-account
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
  scan:
    base-packages:
    - com.sly.fescar.account.service
#========================================spring config=====================================
spring:
  application:
    name: fescar-dubbo-account
#========================================MySQL config=====================================
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.142.209:3306/fescardubbo?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    name: root
    password: 123456
#========================================mybatis config=====================================
mybatis:
  mapper-locations:
  - classpath*:/mapper/*.xml